
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ccf: <http://purl.org/ccf/>
PREFIX has_characterizing_biomarker_set: <http://purl.obolibrary.org/obo/RO_0015004>

SELECT DISTINCT ?node_id (SAMPLE(?node_label) as ?node_label)
WHERE {
  ?node rdfs:label ?label .

  FILTER(CONTAINS(?node_id, ' ') && !STRSTARTS(?node_id, 'HRA latest/'))
  BIND(
    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
      STR(?node),
      "http://purl.obolibrary.org/obo/UBERON_", "UBERON "),
      "http://purl.obolibrary.org/obo/LMHA_", "LMHA "),
      "http://purl.org/sig/ont/fma/fma", "FMA "),
      "http://identifiers.org/hgnc/", "HGNC "),
      "http://purl.obolibrary.org/obo/CL_", "CL "),
      "http://purl.obolibrary.org/obo/PCL_", "PCL "),
      "https://purl.org/ccf/ASCTB-TEMP_", "HRA temp-"),
      "http://purl.org/ccf/", "HRA ")
  as ?node_id)
  BIND(STR(?label) as ?node_label)
}
GROUP BY ?node_id
